services:
  front:
    build: ./game/front
    image: front
    container_name: front
    ports:
      - "5173:5173"
    networks:
      - transcendence
    volumes:
      - ./game/front:/usr/src/app
    init: true
    restart: on-failure
  backend:
    build: ./game/backend
    image: backend
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - transcendence
    volumes:
      - ./game/backend:/usr/src/app
    init: true
    restart: on-failure
  # redis:
  #   image: redis
  #   container_name: redis
  #   ports:
  #     -
networks:
  transcendence:
    name: transcendence